### PR TITLE
fix: Cells are hidden when missing category data

### LINKED ISSUE #240: Some cells missing when loading from a CSV
## Description

Some images are missing in CFE's plot view if they have blank/missing values for the groupby column. (Cell ID by default)

## Expected Behavior

All rows in the CSV should be shown on the plot. A placeholder "(Blank)" or "(N/A)" should be added as a group for any cells missing from the groupby column.

## Reproduction

- See CSV uploaded here, which has five cells (rows): http://dev-aics-dtp-001.corp.alleninstitute.org/users/peyton.lee/cfe-missing-data.csv
- Open http://dev-aics-dtp-001.corp.alleninstitute.org/cell-feature-explorer/dist/?dataset=csv&csvUrl=http://dev-aics-dtp-001.corp.alleninstitute.org/users/peyton.lee/cfe-missing-data.csv
- There should be five cells, but there are only three.

Image

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #240, "Some cells missing when loading from a CSV."

Fixes a bug where images excluded from the current groupBy feature would be hidden in the legends panel. Now, placeholders labeled "(N/A)" will appear to represent missing data, and missing values have a default grey color in the main plot.

*Estimated review size: small, 10-15 minutes*

Solution
========
- If a groupBy feature has cells with missing data, it will now include those as a visible row in the interactive legend on the left, allowing them to be toggled on and off.
- Added a fallback color option in the Plotly configuration for missing data, so they are assigned a grey color by default.
- Added a count for the number of missing cells so they are shown in the color by menu.

Misc:
- Fixed a bug where the default plot ranges would cut off scatterplot points by adding some additional padding.

## Type of change

* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. Open current broken CFE build: https://cfe.allencell.org/?dataset=csv&csvUrl=https%253A%252F%252Fvast-files.int.allencell.org%252Fusers%252Fpeyton.lee%252Ftest-data%252Fcfe-empty-categories.csv
2. Switch the Group by feature to "Feature 4". Note that the total number of cells does not match between the color legend and the checkbox legend.
3.  Open the preview fixed build: https://allen-cell-animated.github.io/cell-feature-explorer/pr-preview/pr-258/?dataset=csv&csvUrl=https%253A%252F%252Fvast-files.int.allencell.org%252Fusers%252Fpeyton.lee%252Ftest-data%252Fcfe-empty-categories.csv
4. Repeat the above. You should see a new "(N/A)" category appear, with the correct count of missing cells.

Screenshots (optional):
-----------------------
**Video talk-through (🔊):**

https://github.com/user-attachments/assets/c68b61fe-5b4f-46e4-887d-ea251a3c5a45

image

image

### CODE REVIEW

File: src/components/MainPlot/index.tsx
Comment (ShrimpCryptid) [inline src/components/MainPlot/index.tsx]: Fixes a bug where the default plot ranges would cut off scatterplot points by adding some additional padding.

File: src/containers/ColorByMenu/selectors.ts [hunk 1]
```diff
@@ -139,11 +143,22 @@ export const getInteractivePanelData = createSelector(
             {} as { [key: string]: number }
         );
 
+        if (countsByCategory[MISSING_CATEGORY_KEY] > 0) {
+            // Some data points have no data for this category. Modify categories
+            // to include an N/A entry.
+            categories = [
```
Comment (toloudis) [inline src/containers/ColorByMenu/selectors.ts]: Nit: I wonder if this would be a little more efficient to just do `categories.push({color,name,key})` instead of the full spread operator
