### PR TITLE
fix: Full field toggle is no longer visible on datasets without full field

### LINKED ISSUE #174: full field is still available for datasets without them
## Description

user can click Full Field in 3d viewer and get loading errors.  

## Expected Behavior

should be disabled when dataset doens't provide full field images

## Reproduction

http://staging.cfe.allencell.org/?cellSelectedFor3D=F2492C26&colorBy=cell-age&dataset=cellsystems_live_v2021.1&plotByOnX=expert-score&plotByOnY=cos&selectedPoint%5B0%5D=F1687C16&selectedPoint%5B1%5D=F2492C26 > Select a datapoint which adds it to the gallery > click the image in the gallery > click "Full field"

CFE Bug Bash - Google Sheets 2024-09-03 09-21-47

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #174, "full field is still visible for datasets without it."

I've thrown in a couple other misc. changes but this is a small PR (<20 lines). Most of the line count comes from dependency changes.

*Estimated review size: tiny, <5 minutes*

Solution
========
- Passes an empty string if the `fovPath` is an empty string.
- Fixes formatting on the left toolbar in the viewport.
- Adds the `ViewerStateProvider` as per the new W3CV API.
- Upgrade web-3d-viewer to v2.9.2

## Type of change
Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. Clone and run `npm run start`.
2. Open http://localhost:9002/?cellSelectedFor3D=439543&colorBy=cell-line&dataset=variance_v1&plotByOnX=cell-volume&plotByOnY=dna-volume&selectedPoint%5B0%5D=439543. You should see the full field toggle.
3. Open http://localhost:9002/?cellSelectedFor3D=F2492C26&colorBy=cell-age&dataset=cellsystems_live_v2021.1&plotByOnX=expert-score&plotByOnY=cos&selectedPoint%5B0%5D=F2492C26. You should not see the full field toggle.

Screenshots (optional):
-----------------------
Full field available:
image

Full field not available:
image

### CODE REVIEW

File: src/components/CellViewer/index.tsx [hunk 1]
```diff
@@ -19,19 +19,21 @@ const CellViewer: React.FunctionComponent<VolumeViewerProps> = (props) => {
...
-                metadata={props.metadata}
-                appHeight="100%"
-                canvasMargin="0 0 0 0"
-            />
+            <ViewerStateProvider>
+                <ImageViewerApp
+                    cellId={props.cellId}
+                    imageUrl={props.baseUrl + props.cellPath}
+                    imageDownloadHref={props.cellDownloadHref}
+                    parentImageUrl={props.fovPath ? props.baseUrl + props.fovPath : ""}
```
Comment (ShrimpCryptid) [inline src/components/CellViewer/index.tsx:27]: This is easier to see with whitespace disabled, but all I did was change this to return an empty string if `props.fovPath` is an empty string.

File: package.json [hunk 2]
```diff
@@ -83,7 +83,7 @@
     },
     "dependencies": {
         "@aics/browsing-context-messaging": "~1.1",
-        "@aics/web-3d-viewer": "^2.9.0",
+        "@aics/web-3d-viewer": "^2.9.2",
```
Comment (toloudis) [inline package.json:86]: do you have a rough idea of what changed from 2.9.0 to 2.9.2?

**Review by toloudis — APPROVED** [review]

File: package.json (hunk 2 above)
Comment (ShrimpCryptid) [reply package.json:86]: There's a lot of changes, basically everything that's been merged since May of this year. The main reason I upgraded was to add in the viewer state refactor (so I can add in ViewerStateProvider).

I'll wait to release CFE until after https://github.com/allen-cell-animated/website-3d-cell-viewer/pull/321 is merged and included in a release.

**Review by frasercl — APPROVED** [review]
