### PR TITLE
fix: Fixed bug where metadata was overwritten by parsed Vol-E params

### LINKED ISSUE #272: Metadata does not appear in Vol-E view
## Description

Metadata for selected cells does not appear in metadata panel in Vol-E.

## Expected Behavior

Metadata should appear. Any feature columns in a CSV should also appear as metadata.

## Reproduction

https://cfe.allencell.org/?cellSelectedFor3D=6086&colorBy=Gene&dataset=csv&csvUrl=https%253A%252F%252Fvast-files.int.allencell.org%252Frep_learn%252FMF%252FOV%252Ffeatures_subset_data_voxel%252Fres%252Fembeddings_val_sub_structure.csv&plotByOnX=tsne_2&plotByOnY=tsne_1&groupBy=Cell%20Line&selectedPoint%5B0%5D=3006&selectedPoint%5B1%5D=6086&selectedPoint%5B2%5D=16659&selectedPoint%5B3%5D=2819

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

### PR DESCRIPTION
**Pull request by ShrimpCryptid**
Problem
=======
Closes #272, "Metadata does not appear in Vol-E view."

When the `url` parameter is defined in the Vol-E URL column of a dataset, the URL parsing logic returns an array containing `undefined` for each URL included, which overwrote the existing feature metadata.

I resolved this bug by adding a method to combine existing metadata with returned Vol-E metadata instead.

*Estimated review size: small, 5-10 minutes*

Solution
========
- Combined existing metadata with Vol-E metadata when Vol-E has app props parsed from the CSV column.

## Type of change
* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. Open PR preview: https://allen-cell-animated.github.io/cell-feature-explorer/pr-preview/pr-280/?cellSelectedFor3D=15252&colorBy=Gene&dataset=csv&csvUrl=https%253A%252F%252Fvast-files.int.allencell.org%252Frep_learn%252FMF%252FOV%252Ffeatures_subset_data_voxel%252Fres%252Fembeddings_val_sub_structure.csv
2. Navigate to the 3D view and click on the metadata tab. The metadata will appear.

Screenshots (optional):
-----------------------
image

### CODE REVIEW

File: src/containers/Cfe/selectors.ts [hunk 1]
```diff
@@ -1,5 +1,8 @@
+import { AppProps, ViewerChannelSettings, ViewerState } from "@aics/vole-app";
+import type { MetadataRecord } from "@aics/vole-app/type-declarations/aics-image-viewer/shared/types";
```
Comment (frasercl) [inline src/containers/Cfe/selectors.ts]: Whoops! That should be top-level exported from Vol-E.

File: src/containers/Cfe/selectors.ts [hunk 2]
```diff
@@ -31,7 +33,7 @@ export interface VolumeViewerProps {
         translation: [number, number, number];
         rotation: [number, number, number];
     };
-    metadata?: { [key: string]: string | number | null };
+    metadata?: MetadataRecord | (MetadataRecord | undefined)[];
```
Comment (frasercl) [inline src/containers/Cfe/selectors.ts]: ...though alternatively, this could have the type `AppProps["metadata"]`

File: src/containers/Cfe/selectors.ts [hunk 3]
```diff
@@ -1,5 +1,8 @@
+import { AppProps, ViewerChannelSettings, ViewerState } from "@aics/vole-app";
```
Comment (frasercl) [inline src/containers/Cfe/selectors.ts]:
```suggestion
import type { AppProps, ViewerChannelSettings, ViewerState } from "@aics/vole-app";
```

File: src/containers/Cfe/selectors.ts [hunk 4]
```diff
@@ -75,6 +77,23 @@ const getCellMetadata = createSelector(
     }
 );
 
+const combineVoleMetadata = (
+    voleMetadata: VolumeViewerProps["metadata"],
```
Comment (frasercl) [inline src/containers/Cfe/selectors.ts]: Huh... why does `VolumeViewerProps` exist as a separate type in this repo? Looks like it may just duplicate some fields of `AppProps` from vole-app?

Probably out of scope for this tiny change to reorg this though

**Review by frasercl — APPROVED** [review]

**Review by meganrm — APPROVED** [review]

File: src/containers/Cfe/selectors.ts (hunk 4 above)
Comment (ShrimpCryptid) [reply src/containers/Cfe/selectors.ts]: Adding a TODO about it, yeah
